executor: slurm

default-resources:
  - mem_mb_per_cpu=4000
  - cpus_per_task=1
  - runtime=60
  - slurm_partition="normal"
  - slurm_jobname="smk_{rule}"

jobs: 800
latency-wait: 30
rerun-incomplete: true

slurm-logdir: logs
use-envmodules: true